{
 "title": "Chains",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(tendermint_mempool_size,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{job=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Signed Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_last_signed_height{job=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks rate per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "delta(tendermint_consensus_height{job=\"$node\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Txs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{job=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed blocks",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "changes(tendermint_consensus_validator_missed_blocks{job=\"$node\"}[$__interval])",
     "legendFormat": "num"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "tendermint_consensus_validators{job=\"$node\"}",
     "legendFormat": "active"
    },
    {
     "expr": "tendermint_consensus_missing_validators{job=\"$node\"}",
     "legendFormat": "missed"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators{job=\"$node\"}",
     "legendFormat": "byzantine"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{job=\"$node\"}",
     "legendFormat": "block size"
    }
   ]
  },
  {
   "title": "Total Txs/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "rate(tendermint_consensus_num_txs{job=\"$node\"}[1m])",
     "legendFormat": "Txs/sec"
    }
   ]
  },
  {
   "title": "Peers count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{job=\"$node\"}",
     "legendFormat": "num"
    }
   ]
  },
  {
   "title": "Failed Txs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "tendermint_mempool_failed_txs{jon=\"$node\"}",
     "legendFormat": "num"
    }
   ]
  },
  {
   "title": "Block interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds{}",
     "legendFormat": "Txs/sec"
    }
   ]
  },
  {
   "title": "Total Network Input",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(tendermint_p2p_peer_receive_bytes_total{job=\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Network Output",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(tendermint_p2p_peer_send_bytes_total{job=\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}